#!/usr/bin/env python3
"""
render_fill_docs_prompt.py — Generate a ready-to-paste doc-fill prompt

Reads docs/app-intake.md from a generated app repo, combines it with the
fill-docs-from-intake prompt, and outputs a single paste-ready block.

Also writes the prompt to .tmp/fill-docs-prompt.md in the project
so it can be opened and copied from inside VS Code.

Usage:
    python3 scripts/render_fill_docs_prompt.py [project-path]

    project-path defaults to the current directory.

Examples:
    fill-docs                           # from inside the project
    fill-docs ~/projects/my-startup     # from anywhere
    fill-docs .                         # explicit current dir
"""

import re
import sys
from pathlib import Path


FACTORY_ROOT = Path(__file__).parent.parent
PROMPT_FILE  = FACTORY_ROOT / "prompts" / "fill-docs-from-intake.md"


# ─── Loaders ──────────────────────────────────────────────────────────────────

def load_prompt_body():
    """
    Load the fill-docs prompt body — everything after the first --- separator.
    The factory header (instructions for manual use) is above that line.
    """
    if not PROMPT_FILE.exists():
        abort(f"Prompt file not found: {PROMPT_FILE}")

    content = PROMPT_FILE.read_text(encoding="utf-8")
    parts   = content.split("---", maxsplit=1)

    if len(parts) < 2:
        abort(f"No --- separator found in {PROMPT_FILE}")

    return parts[1].strip()


def load_intake(project_dir):
    intake_path = project_dir / "docs" / "app-intake.md"

    if not intake_path.exists():
        abort(
            f"docs/app-intake.md not found in:\n  {project_dir}\n\n"
            "Make sure you're pointing at a project generated by app-factory.\n"
            "Run from inside the project: fill-docs\n"
            "Or pass the path: fill-docs ~/projects/my-startup"
        )

    return intake_path.read_text(encoding="utf-8")


# ─── Validation ───────────────────────────────────────────────────────────────

def validate_intake(intake_content):
    """
    Return a list of warning strings if the intake looks incomplete.
    All checks are non-fatal — warnings only.
    """
    warnings = []

    # Uncleared generator placeholders (e.g. {{ONE_LINE_DESCRIPTION}})
    placeholders = sorted(set(re.findall(r"\{\{[A-Z_0-9]+\}\}", intake_content)))
    if placeholders:
        sample = placeholders[0]
        warnings.append(
            f"{len(placeholders)} generator placeholder(s) still present "
            f"(e.g. {sample}) — fill or delete them"
        )

    # Empty numbered workflow steps ("1." or "3." with nothing after)
    empty_steps = re.findall(r"^\d+\.\s*$", intake_content, re.MULTILINE)
    if len(empty_steps) >= 3:
        warnings.append(
            f"Core workflow looks incomplete ({len(empty_steps)} empty step(s)) "
            "— this is the most important section"
        )

    # Low content density: fewer than 8 substantive lines suggests mostly unfilled
    content_lines = [
        line for line in intake_content.splitlines()
        if (
            line.strip()
            and not line.strip().startswith("#")
            and not line.strip().startswith("<!--")
            and not line.strip().startswith("**")
            and not line.strip().startswith("---")
            and not re.match(r"^\d+\.\s*$", line.strip())
        )
    ]
    if len(content_lines) < 8:
        warnings.append(
            "Intake looks mostly unfilled — consider completing it before proceeding"
        )

    return warnings


# ─── Prompt builder ───────────────────────────────────────────────────────────

def build_composite(intake_content, prompt_body):
    """
    Combine intake content and prompt instructions into a single paste-ready block.

    The intake is embedded inline so Claude does not need to read a separate file.
    The prompt body is adjusted to reflect this.
    """
    # Redirect Claude to use the inlined content instead of reading the file
    prompt_body = prompt_body.replace(
        "Read `docs/app-intake.md` first. That is your primary source of truth.",
        "The intake doc is provided above — use it as your primary source of truth.\n"
        "Do not read `docs/app-intake.md` separately; the content above is the same.",
    )

    return (
        "Here is my completed app intake:\n\n"
        "---\n"
        f"{intake_content.strip()}\n"
        "---\n\n"
        f"{prompt_body}"
    )


# ─── Helpers ──────────────────────────────────────────────────────────────────

def abort(message):
    print(f"\nError: {message}\n", file=sys.stderr)
    sys.exit(1)


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    project_dir = (
        Path(sys.argv[1]).expanduser().resolve()
        if len(sys.argv) > 1
        else Path.cwd()
    )

    if not project_dir.is_dir():
        abort(f"Directory not found: {project_dir}")

    intake_content = load_intake(project_dir)
    prompt_body    = load_prompt_body()

    # Warn if intake looks incomplete — non-fatal
    warnings = validate_intake(intake_content)
    if warnings:
        print(file=sys.stderr)
        for w in warnings:
            print(f"  Warning: {w}", file=sys.stderr)
        print(file=sys.stderr)

    composite = build_composite(intake_content, prompt_body)

    # Write to .tmp/ so it's accessible inside VS Code
    tmp_dir  = project_dir / ".tmp"
    tmp_dir.mkdir(exist_ok=True)
    out_path = tmp_dir / "fill-docs-prompt.md"
    out_path.write_text(composite, encoding="utf-8")

    # Print with clear delimiters
    w = 62
    print()
    print("═" * w)
    print("  FILL DOCS PROMPT — paste into Claude Code")
    print("═" * w)
    print()
    print(composite)
    print()
    print("═" * w)
    print(f"\n  Saved: {out_path}")
    print()


if __name__ == "__main__":
    main()
